package com.example.ustc_pc.myapplication.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COURSE".
 */
public class Course {

    private Long id;
    private String strCourseName;
    private Integer iCourseID;
    private Boolean isSelected=false;
    private Integer iUserID;

    public Course() {
    }

    public Course(Long id) {
        this.id = id;
    }

    public Course(Long id, String strCourseName, Integer iCourseID, Boolean isSelected, Integer iUserID) {
        this.id = id;
        this.strCourseName = strCourseName;
        this.iCourseID = iCourseID;
        this.isSelected = isSelected;
        this.iUserID = iUserID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStrCourseName() {
        return strCourseName;
    }

    public void setStrCourseName(String strCourseName) {
        this.strCourseName = strCourseName;
    }

    public Integer getICourseID() {
        return iCourseID;
    }

    public void setICourseID(Integer iCourseID) {
        this.iCourseID = iCourseID;
    }

    public Boolean getIsSelected() {
        return isSelected;
    }

    public void setIsSelected(Boolean isSelected) {
        this.isSelected = isSelected;
    }

    public Integer getIUserID() {
        return iUserID;
    }

    public void setIUserID(Integer iUserID) {
        this.iUserID = iUserID;
    }

}
