package com.example.ustc_pc.myapplication.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig courseDaoConfig;
    private final DaoConfig kPsDaoConfig;
    private final DaoConfig doneQuestionDaoConfig;

    private final UserDao userDao;
    private final CourseDao courseDao;
    private final KPsDao kPsDao;
    private final DoneQuestionDao doneQuestionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        kPsDaoConfig = daoConfigMap.get(KPsDao.class).clone();
        kPsDaoConfig.initIdentityScope(type);

        doneQuestionDaoConfig = daoConfigMap.get(DoneQuestionDao.class).clone();
        doneQuestionDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        courseDao = new CourseDao(courseDaoConfig, this);
        kPsDao = new KPsDao(kPsDaoConfig, this);
        doneQuestionDao = new DoneQuestionDao(doneQuestionDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Course.class, courseDao);
        registerDao(KPs.class, kPsDao);
        registerDao(DoneQuestion.class, doneQuestionDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        courseDaoConfig.getIdentityScope().clear();
        kPsDaoConfig.getIdentityScope().clear();
        doneQuestionDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public KPsDao getKPsDao() {
        return kPsDao;
    }

    public DoneQuestionDao getDoneQuestionDao() {
        return doneQuestionDao;
    }

}
