package com.example.ustc_pc.myapplication.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "DONE_QUESTION".
 */
public class DoneQuestion implements Serializable{

    private Integer iCourseID;
    private Integer iQuestionType;
    private Integer iQuestionID;
    private Boolean isFavorite;
    private Boolean isCorrect;
    private String strNote;
    private String strUserAnswer;
    private Long iSpendTime;
    private String strKPID;

    public DoneQuestion() {
    }

    public DoneQuestion(Integer iCourseID, Integer iQuestionType, Integer iQuestionID, Boolean isFavorite, Boolean isCorrect, String strNote, String strUserAnswer, Long iSpendTime, String strKPID) {
        this.iCourseID = iCourseID;
        this.iQuestionType = iQuestionType;
        this.iQuestionID = iQuestionID;
        this.isFavorite = isFavorite;
        this.isCorrect = isCorrect;
        this.strNote = strNote;
        this.strUserAnswer = strUserAnswer;
        this.iSpendTime = iSpendTime;
        this.strKPID = strKPID;
    }

    public Integer getICourseID() {
        return iCourseID;
    }

    public void setICourseID(Integer iCourseID) {
        this.iCourseID = iCourseID;
    }

    public Integer getIQuestionType() {
        return iQuestionType;
    }

    public void setIQuestionType(Integer iQuestionType) {
        this.iQuestionType = iQuestionType;
    }

    public Integer getIQuestionID() {
        return iQuestionID;
    }

    public void setIQuestionID(Integer iQuestionID) {
        this.iQuestionID = iQuestionID;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public Boolean getIsCorrect() {
        return isCorrect;
    }

    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }

    public String getStrNote() {
        return strNote;
    }

    public void setStrNote(String strNote) {
        this.strNote = strNote;
    }

    public String getStrUserAnswer() {
        return strUserAnswer;
    }

    public void setStrUserAnswer(String strUserAnswer) {
        this.strUserAnswer = strUserAnswer;
    }

    public Long getISpendTime() {
        return iSpendTime;
    }

    public void setISpendTime(Long iSpendTime) {
        this.iSpendTime = iSpendTime;
    }

    public String getStrKPID() {
        return strKPID;
    }

    public void setStrKPID(String strKPID) {
        this.strKPID = strKPID;
    }

}
