package com.example.ustc_pc.myapplication.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DONE_QUESTION".
 */
public class DoneQuestion {

    private Integer iCourseID;
    private Integer iQuestionType;
    private Integer iQuestionID;
    private Boolean isFavorite = false;
    private Boolean isCorrect = false;
    private String strNote;
    private String strUserAnswer;
    private Integer iSpendTime;

    public DoneQuestion() {
    }

    public DoneQuestion(Integer iCourseID, Integer iQuestionType, Integer iQuestionID, Boolean isFavorite, Boolean isCorrect, String strNote, String strUserAnswer, Integer iSpendTime) {
        this.iCourseID = iCourseID;
        this.iQuestionType = iQuestionType;
        this.iQuestionID = iQuestionID;
        this.isFavorite = isFavorite;
        this.isCorrect = isCorrect;
        this.strNote = strNote;
        this.strUserAnswer = strUserAnswer;
        this.iSpendTime = iSpendTime;
    }

    public Integer getICourseID() {
        return iCourseID;
    }

    public void setICourseID(Integer iCourseID) {
        this.iCourseID = iCourseID;
    }

    public Integer getIQuestionType() {
        return iQuestionType;
    }

    public void setIQuestionType(Integer iQuestionType) {
        this.iQuestionType = iQuestionType;
    }

    public Integer getIQuestionID() {
        return iQuestionID;
    }

    public void setIQuestionID(Integer iQuestionID) {
        this.iQuestionID = iQuestionID;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public Boolean getIsCorrect() {
        return isCorrect;
    }

    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }

    public String getStrNote() {
        return strNote;
    }

    public void setStrNote(String strNote) {
        this.strNote = strNote;
    }

    public String getStrUserAnswer() {
        return strUserAnswer;
    }

    public void setStrUserAnswer(String strUserAnswer) {
        this.strUserAnswer = strUserAnswer;
    }

    public Integer getISpendTime() {
        return iSpendTime;
    }

    public void setISpendTime(Integer iSpendTime) {
        this.iSpendTime = iSpendTime;
    }

}
