package com.example.ustc_pc.myapplication.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "KPS".
 */
public class KPs implements Serializable, Comparable<KPs>{

    private Long id;
    private Integer iUserID;
    private Boolean isExpand;
    private String strKPID;
    private Integer iCourseID;
    private String strName;
    private Integer iLevel;
    private String strFatherKPID;
    private Boolean hasChild;
    private Integer iProgress;

    @Override
    public boolean equals(Object object){
        return getStrKPID().equals(((KPs)object).getStrKPID());
    }

    @Override
    public int compareTo(KPs kPs) {
        return this.getStrKPID().compareTo(kPs.getStrKPID());
    }

    public KPs() {
    }

    public KPs(Long id) {
        this.id = id;
    }

    public KPs(Long id, Integer iUserID, Boolean isExpand, String strKPID, Integer iCourseID, String strName, Integer iLevel, String strFatherKPID, Boolean hasChild, Integer iProgress) {
        this.id = id;
        this.iUserID = iUserID;
        this.isExpand = isExpand;
        this.strKPID = strKPID;
        this.iCourseID = iCourseID;
        this.strName = strName;
        this.iLevel = iLevel;
        this.strFatherKPID = strFatherKPID;
        this.hasChild = hasChild;
        this.iProgress = iProgress;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIUserID() {
        return iUserID;
    }

    public void setIUserID(Integer iUserID) {
        this.iUserID = iUserID;
    }

    public Boolean getIsExpand() {
        return isExpand;
    }

    public void setIsExpand(Boolean isExpand) {
        this.isExpand = isExpand;
    }

    public String getStrKPID() {
        return strKPID;
    }

    public void setStrKPID(String strKPID) {
        this.strKPID = strKPID;
    }

    public Integer getICourseID() {
        return iCourseID;
    }

    public void setICourseID(Integer iCourseID) {
        this.iCourseID = iCourseID;
    }

    public String getStrName() {
        return strName;
    }

    public void setStrName(String strName) {
        this.strName = strName;
    }

    public Integer getILevel() {
        return iLevel;
    }

    public void setILevel(Integer iLevel) {
        this.iLevel = iLevel;
    }

    public String getStrFatherKPID() {
        return strFatherKPID;
    }

    public void setStrFatherKPID(String strFatherKPID) {
        this.strFatherKPID = strFatherKPID;
    }

    public Boolean getHasChild() {
        return hasChild;
    }

    public void setHasChild(Boolean hasChild) {
        this.hasChild = hasChild;
    }

    public Integer getIProgress() {
        return iProgress;
    }

    public void setIProgress(Integer iProgress) {
        this.iProgress = iProgress;
    }

}
