package com.example.ustc_pc.myapplication.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private Integer iUserID;
    private String strPhoneNumber;
    private String strUserName;
    private Integer iGender;
    private String strEmail;
    private String strAboutMe;
    private Integer iUserType;
    private String strSourceCollege;
    private String strSourceMajor;
    private String strFirstTargetCollege;
    private String strFirstTargetMajor;
    private String strSecondTargetCollege;
    private String strSecondTargetMajor;
    private String strAcceptedCollege;
    private String strAcceptedMajor;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Integer iUserID, String strPhoneNumber, String strUserName, Integer iGender, String strEmail, String strAboutMe, Integer iUserType, String strSourceCollege, String strSourceMajor, String strFirstTargetCollege, String strFirstTargetMajor, String strSecondTargetCollege, String strSecondTargetMajor, String strAcceptedCollege, String strAcceptedMajor) {
        this.id = id;
        this.iUserID = iUserID;
        this.strPhoneNumber = strPhoneNumber;
        this.strUserName = strUserName;
        this.iGender = iGender;
        this.strEmail = strEmail;
        this.strAboutMe = strAboutMe;
        this.iUserType = iUserType;
        this.strSourceCollege = strSourceCollege;
        this.strSourceMajor = strSourceMajor;
        this.strFirstTargetCollege = strFirstTargetCollege;
        this.strFirstTargetMajor = strFirstTargetMajor;
        this.strSecondTargetCollege = strSecondTargetCollege;
        this.strSecondTargetMajor = strSecondTargetMajor;
        this.strAcceptedCollege = strAcceptedCollege;
        this.strAcceptedMajor = strAcceptedMajor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIUserID() {
        return iUserID;
    }

    public void setIUserID(Integer iUserID) {
        this.iUserID = iUserID;
    }

    public String getStrPhoneNumber() {
        return strPhoneNumber;
    }

    public void setStrPhoneNumber(String strPhoneNumber) {
        this.strPhoneNumber = strPhoneNumber;
    }

    public String getStrUserName() {
        return strUserName;
    }

    public void setStrUserName(String strUserName) {
        this.strUserName = strUserName;
    }

    public Integer getIGender() {
        return iGender;
    }

    public void setIGender(Integer iGender) {
        this.iGender = iGender;
    }

    public String getStrEmail() {
        return strEmail;
    }

    public void setStrEmail(String strEmail) {
        this.strEmail = strEmail;
    }

    public String getStrAboutMe() {
        return strAboutMe;
    }

    public void setStrAboutMe(String strAboutMe) {
        this.strAboutMe = strAboutMe;
    }

    public Integer getIUserType() {
        return iUserType;
    }

    public void setIUserType(Integer iUserType) {
        this.iUserType = iUserType;
    }

    public String getStrSourceCollege() {
        return strSourceCollege;
    }

    public void setStrSourceCollege(String strSourceCollege) {
        this.strSourceCollege = strSourceCollege;
    }

    public String getStrSourceMajor() {
        return strSourceMajor;
    }

    public void setStrSourceMajor(String strSourceMajor) {
        this.strSourceMajor = strSourceMajor;
    }

    public String getStrFirstTargetCollege() {
        return strFirstTargetCollege;
    }

    public void setStrFirstTargetCollege(String strFirstTargetCollege) {
        this.strFirstTargetCollege = strFirstTargetCollege;
    }

    public String getStrFirstTargetMajor() {
        return strFirstTargetMajor;
    }

    public void setStrFirstTargetMajor(String strFirstTargetMajor) {
        this.strFirstTargetMajor = strFirstTargetMajor;
    }

    public String getStrSecondTargetCollege() {
        return strSecondTargetCollege;
    }

    public void setStrSecondTargetCollege(String strSecondTargetCollege) {
        this.strSecondTargetCollege = strSecondTargetCollege;
    }

    public String getStrSecondTargetMajor() {
        return strSecondTargetMajor;
    }

    public void setStrSecondTargetMajor(String strSecondTargetMajor) {
        this.strSecondTargetMajor = strSecondTargetMajor;
    }

    public String getStrAcceptedCollege() {
        return strAcceptedCollege;
    }

    public void setStrAcceptedCollege(String strAcceptedCollege) {
        this.strAcceptedCollege = strAcceptedCollege;
    }

    public String getStrAcceptedMajor() {
        return strAcceptedMajor;
    }

    public void setStrAcceptedMajor(String strAcceptedMajor) {
        this.strAcceptedMajor = strAcceptedMajor;
    }

}
